import React, { useEffect, useMemo, useState } from "react";
import { apiClient } from "@/utils/apiClient";

type Activity = { id: number; user_name: string; username: string; activity_type: string; value: number; points: number; recorded_at: string };
const labels: Record<string, string> = { running: "Running", walking: "Walking", cycling: "Cycling", swimming: "Swimming", gym: "Gym", daily_steps: "Daily steps" };
const units: Record<string, string> = { running: "km", walking: "km", cycling: "km", swimming: "min", gym: "min", daily_steps: "steps" };

export const AdminActivityHistoryPage: React.FC = () => {
  const [activities, setActivities] = useState<Activity[]>([]);
  const [query, setQuery] = useState("");
  useEffect(() => { apiClient.get<Activity[]>("/admin/activities").then((response) => setActivities(response.data)).catch(() => {}); }, []);
  const shownActivities = useMemo(() => activities.filter((activity) => `${activity.user_name} ${activity.username} ${labels[activity.activity_type]}`.toLowerCase().includes(query.toLowerCase())), [activities, query]);
  return <main className="min-h-screen bg-[#fffaf7] px-4 py-7 text-slate-900 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1280px]"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Activity history</h1><p className="mt-1 text-slate-500">All activity entries recorded by clients.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search activities" className="rounded-lg border border-stone-200 bg-white px-4 py-2 text-sm outline-none focus:border-orange-500" /></header><section className="mt-6 overflow-hidden rounded-2xl border border-stone-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="border-b border-stone-100 bg-stone-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Client</th><th className="px-6 py-4">Activity</th><th className="px-6 py-4">Metric</th><th className="px-6 py-4">Date</th><th className="px-6 py-4 text-right">Points</th></tr></thead><tbody className="divide-y divide-stone-100">{shownActivities.map((activity) => <tr key={activity.id} className="text-sm"><td className="px-6 py-4"><b>{activity.user_name}</b><p className="mt-1 text-xs text-slate-500">@{activity.username}</p></td><td className="px-6 py-4">{labels[activity.activity_type]}</td><td className="px-6 py-4 text-slate-600">{activity.value.toLocaleString()} {units[activity.activity_type]}</td><td className="px-6 py-4 text-slate-600">{new Date(activity.recorded_at).toLocaleDateString()}</td><td className="px-6 py-4 text-right font-bold text-orange-600">{activity.points.toLocaleString()}</td></tr>)}{!shownActivities.length && <tr><td colSpan={5} className="px-6 py-16 text-center text-slate-500">No activities found.</td></tr>}</tbody></table></div></section></div></main>;
};
